CREATE TABLE T_STATUS(
    STA_CODIGO VARCHAR(2) NOT NULL,
    STA_NOME VARCHAR(50) NOT NULL,
    STA_COR VARCHAR(20) NOT NULL,

    PRIMARY KEY (STA_CODIGO)
);

INSERT INTO T_STATUS(STA_CODIGO, STA_NOME, STA_COR) VALUES 
('CD', 'EXAME CADASTRADO', 'LARANJA'),
('MC', 'MATERIAL COLETADO', 'AZULESCURO'),
('MT', 'MATERIAL TRIADO', 'AMARELO'),
('RI', 'RESULTADO INFORMADO', 'ROSA'),
('RL', 'RESULTADO LIBERADO', 'VERDE'),
('SR', 'SOLICITADO RECOLETA', 'ROXO'),
('CA', 'CANCELADO', 'VERMELHO');
