CREATE TABLE T_REQUISICAO(
    REQ_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    MED_CODIGO BIGINT,
    REQ_DATA DATETIME NOT NULL,
    REQ_URGENTE TINYINT NOT NULL,
    PES_CODIGO BIGINT NOT NULL,
    USU_CODIGO BIGINT NOT NULL,
    REQ_PAGA TINYINT NOT NULL,
    REQ_PRECO_TOTAL DECIMAL(7,2) NOT NULL,

    PRIMARY KEY (REQ_CODIGO),
    FOREIGN KEY (MED_CODIGO) REFERENCES T_MEDICO(MED_CODIGO),
    FOREIGN KEY (PES_CODIGO) REFERENCES T_PESSOA(PES_CODIGO),
    FOREIGN KEY (USU_CODIGO) REFERENCES T_USUARIO(USU_CODIGO)
);
CREATE TABLE T_REQUISICAO_EXAME(
    REX_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    LAY_CODIGO BIGINT NOT NULL,
    REX_DATAHORA_COLETA DATETIME,
    MRE_CODIGO BIGINT,
    REX_IMPRESSO TINYINT NOT NULL,
    BIO_CODIGO BIGINT,
    BIO_ASSINATURA VARCHAR(MAX),
    REQ_CODIGO BIGINT NOT NULL,
    EXA_CODIGO BIGINT NOT NULL,
    STA_CODIGO VARCHAR(2) NOT NULL,
    REX_DATAHORA_INCLUSAO DATETIME NOT NULL,
    REX_DATAHORA_TRIAGEM DATETIME,
    REX_DATAHORA_LIBERACAO DATETIME,
    
    PRIMARY KEY (REX_CODIGO),
    FOREIGN KEY (LAY_CODIGO) REFERENCES T_LAYOUT(LAY_CODIGO),
    FOREIGN KEY (MRE_CODIGO) REFERENCES T_MOTIVO_RECOLETA(MRE_CODIGO),
    FOREIGN KEY (BIO_CODIGO) REFERENCES T_BIOQUIMICO(BIO_CODIGO),
    FOREIGN KEY (REQ_CODIGO) REFERENCES T_REQUISICAO(REQ_CODIGO),
    FOREIGN KEY (EXA_CODIGO) REFERENCES T_EXAME(EXA_CODIGO),
    FOREIGN KEY (STA_CODIGO) REFERENCES T_STATUS(STA_CODIGO)
);
CREATE TABLE T_REQUISICAO_EXAME_ITENS_RESULTADO(
    REI_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    REX_CODIGO BIGINT NOT NULL,
    REI_DESCRICAO VARCHAR(100),
    REI_CODIGO_CAMPO BIGINT NOT NULL,

    PRIMARY KEY (REI_CODIGO),
    FOREIGN KEY (REX_CODIGO) REFERENCES T_REQUISICAO_EXAME(REX_CODIGO)
);
