CREATE TABLE T_AGENDAMENTO_COLETA(
    ACO_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    ACO_DATAHORA_COLETA_AGENDADA DATETIME,
    PES_CODIGO BIGINT NOT NULL,
    REQ_CODIGO BIGINT NOT NULL,
    USU_CODIGO BIGINT NOT NULL,

    PRIMARY KEY (ACO_CODIGO),
    FOREIGN KEY (PES_CODIGO) REFERENCES T_PESSOA(PES_CODIGO),
    FOREIGN KEY (REQ_CODIGO) REFERENCES T_REQUISICAO(REQ_CODIGO),
    FOREIGN KEY (USU_CODIGO) REFERENCES T_USUARIO(USU_CODIGO)
);
