CREATE TABLE T_ORCAMENTO(
    ORC_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    USU_CODIGO BIGINT NOT NULL,
    PES_CODIGO BIGINT NOT NULL,
    MED_CODIGO BIGINT,
    ORC_DATA DATE NOT NULL,
    ORC_PRECO_TOTAL DECIMAL(7, 2) NOT NULL,

    PRIMARY KEY (ORC_CODIGO),
    FOREIGN KEY (USU_CODIGO) references T_USUARIO(USU_CODIGO),
    FOREIGN KEY (PES_CODIGO) references T_PESSOA(PES_CODIGO),
    FOREIGN KEY (MED_CODIGO) references T_MEDICO(MED_CODIGO)
);

CREATE TABLE T_ORCAMENTO_EXAME(
    OEX_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    ORC_CODIGO BIGINT NOT NULL,
    EXA_CODIGO BIGINT NOT NULL,

    PRIMARY KEY (OEX_CODIGO),
    FOREIGN KEY (ORC_CODIGO) REFERENCES T_ORCAMENTO(ORC_CODIGO),
    FOREIGN KEY (EXA_CODIGO) REFERENCES T_EXAME(EXA_CODIGO)
);
