CREATE TABLE T_HISTORICO(
    HIS_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    HIS_REFERENCIA_CODIGO BIGINT NOT NULL, --Guarda o id de qualquer das tabelas do banco
    HIS_TABELA VARCHAR(50) NOT NULL,
    USU_CODIGO BIGINT NOT NULL,
    HIS_ACAO_TIPO VARCHAR(20) NOT NULL,
    HIS_ACAO_DATAHORA DATETIME NOT NULL,
    HIS_DADOS_ATUALIZADOS TEXT NOT NULL,

    PRIMARY KEY (HIS_CODIGO),
    FOREIGN KEY (USU_CODIGO) REFERENCES T_USUARIO(USU_CODIGO)
);
