CREATE TABLE T_USUARIO(
    USU_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    USU_LOGIN VARCHAR(20) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_ATIVO TINYINT NOT NULL,
    USU_ADMINISTRADOR TINYINT NOT NULL,
    USU_NOME VARCHAR(50) NOT NULL,

    PRIMARY KEY(USU_CODIGO)
);

INSERT INTO T_USUARIO(USU_LOGIN, USU_SENHA, USU_ATIVO, USU_ADMINISTRADOR, USU_NOME) 
VALUES ('admin', '$2a$12$KQSM9izb33mPNP6HbUUiduE/JuxxVExwhBaPXdRHcoDUddgyH2EVS', 1, 1, 'administrador');
