CREATE TABLE T_MEDICO(
    MED_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    MED_EMAIL VARCHAR(50),
    MED_TELEFONE VARCHAR(11),
    MED_CRM VARCHAR(6) NOT NULL,
    MED_UF VARCHAR(2) NOT NULL,
    MED_NOME VARCHAR(50) NOT NULL,

    PRIMARY KEY (MED_CODIGO)
);

INSERT INTO T_MEDICO (MED_EMAIL, MED_TELEFONE, MED_CRM, MED_UF, MED_NOME) VALUES 
('luciano.martin@gmail.com', '49988763423', '26862', 'SC', 'Luciano Martin'),
('andersonsoares@outlook.com', '47988769223', '27632', 'SC', 'Anderson Soares'),
(NULL, NULL, '18888', 'SC', 'Joaquim Souza');
