CREATE TABLE T_SETOR(
    SET_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    SET_NOME VARCHAR(50) NOT NULL,
    SET_DESCRICAO TEXT,

    PRIMARY KEY (SET_CODIGO)
);

INSERT INTO T_SETOR(SET_NOME, SET_DESCRICAO) VALUES 
('Bioquimica', NULL)
('Urinalise', NULL),
('Hematologia', NULL);