CREATE TABLE T_LAYOUT_CAMPOS(
    LCM_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    LCM_CODIGO_CAMPO SMALLINT NOT NULL,
    LAY_CODIGO BIGINT NOT NULL,
    LCM_TIPO VARCHAR(1) NOT NULL,
    LCM_POSICAO SMALLINT NOT NULL, --O LAYOUT É COMPOSTO DE UMA TABELA DE QUADRADOS DE TAMANHO 20 X 28, CADA QUADRADO TEM UM NÚMERO EM SEQUÊNCIA -> 1, 2, 3, 4, 5...
    LCM_ALTURA SMALLINT NOT NULL,
    LCM_LARGURA SMALLINT NOT NULL,
    LCM_TEXTO TEXT,
    LCM_FONTE_COR VARCHAR(2) NOT NULL,
    LCM_FONTE_TAMANHO TINYINT NOT NULL,

    PRIMARY KEY(LCM_CODIGO),

    FOREIGN KEY(LAY_CODIGO) REFERENCES T_LAYOUT(LAY_CODIGO)
);

insert into LayoutCampos(LAY_CODIGO, LCM_CODIGO_CAMPO, LCM_TIPO, LCM_POSICAO, LCM_ALTURA, LCM_LARGURA, LCM_TEXTO, LCM_FONTE_COR, LCM_FONTE_TAMANHO) VALUES
(1, 1, 'T', 22, 1, 40, 'Hemograma simples', 'PT', 4),
(1, 2, 'T', 62, 1, 10, 'Contagem Plaquetas:', 'PT', 3),
(1, 3, 'R', 72, 1, 2, NULL, 'PT', 3),
(1, 4, 'T', 82, 1, 10, 'Contagem Leucocitos:', 'PT', 3),
(1, 5, 'R', 92, 1, 2, NULL, 'PT', 3),
(1, 6, 'T', 102, 1, 10, 'Contagem hemacias:', 'PT', 3),
(1, 7, 'R', 112, 1, 2, NULL, 'PT', 3);    
