spring.datasource.url=jdbc:sqlserver://${HEALTHLAB_API_DB_HOST}:${HEALTHLAB_API_DB_PORT};databaseName=${HEALTHLAB_API_DB_NAME};encrypt=false
spring.datasource.username=${HEALTHLAB_API_DB_USERNAME}
spring.datasource.password=${HEALTHLAB_API_DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.error.include-stacktrace=never

spring.output.ansi.enabled=always

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
