@echo off

SETX HEALTHLAB_API_SECRET "SEU SECRET SUPER SECRETO :D"
SETX HEALTHLAB_API_TTL_TOKEN 3600000
SETX HEALTHLAB_API_DB_HOST "localhost"
SETX HEALTHLAB_API_DB_PORT 1433
SETX HEALTHLAB_API_DB_NAME healthlab
SETX HEALTHLAB_API_DB_USERNAME "sa"
SETX HEALTHLAB_API_DB_PASSWORD "12345678"
